[pytest]
python_files = test_big_files.py, test_term_matrix.py, test_token_stats.py, test_tokenizer.py, test_utils.py     # test_*.py does not work because it also calls test_foo.py which does not belong to the package
data_file = .coverage             # it should point to the coverage data [here incorrect path]
